#version: '3.7'

services:
    symfony_php-fpm:
        image: php:8.3-fpm-alpine
        build:
            dockerfile: docker/php-fpm/Dockerfile
        container_name: 'symfony_php'
        ports:
            - '9000:9000'
        volumes:
            - ./:/app
        working_dir: /app
        networks:
            - net

    symfony_nginx:
        image: nginx
        container_name: 'symfony_nginx'
        working_dir: /app
        ports:
            - '8080:80'
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - net

#Docker Networks
networks:
    net:
        driver: bridge
